POST http://localhost:8080/api/v1/follow/followers/2
Authorization: TOKEN eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaXNzIjoibmFqYWt3aGEiLCJleHAiOjE2MzM0MzIzOTAsImlhdCI6MTYzMzQzMDU5MH0.0ftOOhdd_CsQ_K1-k-8kTzCfRLU-mvx1xd9cHJ6STfYJyL_T_1m3GswylPJst_UO5hrG0sL5VyXjypA6AyZ6ig

###
GET http://localhost:8080/api/v1/follow/followers
Authorization: TOKEN eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaXNzIjoibmFqYWt3aGEiLCJleHAiOjE2MzM0MzIzOTAsImlhdCI6MTYzMzQzMDU5MH0.0ftOOhdd_CsQ_K1-k-8kTzCfRLU-mvx1xd9cHJ6STfYJyL_T_1m3GswylPJst_UO5hrG0sL5VyXjypA6AyZ6ig