### signup1
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "name": "test4567",
    "email": "test4567@jake.jake",
    "password" : "password3"
}

### signup2
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
"name": "jaker",
"email": "jaker2@jaker.jaker",
"password" : "password2"
}

### Login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "test456@jake.jake",
  "password" : "password3"
}

### Logout
POST http://localhost:8080/api/v1/logout

### RE-Login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "jake2@jake.jake",
  "password" : "password2"
}