### 지갑 생성
POST http://localhost:8080/wallet/create
Content-Type: application/json

{
  "email": "jake2@jake.jake",
  "password" : "password2"
}

### 월렉에서 주소값 가져오기
GET http://localhost:8080/wallet/balance?address=0x715b04b5ad4ddc54d344dc1f36a50fbe98b1ec68
