### 지갑 생성
POST http://localhost:8080/login/create/test
Content-Type: application/json

{
  "email": "jake2@jake.jake",
  "password" : "password2"
}

### 월렉에서 주소값 가져오기
GET http://localhost:8080/login/balance/test?address=0x0e98d4ba0a2d2940f6a8c31017287b622ad6e744
