server:
  port: 8080
logging.level:
  org.hibernate.SQL: debug
spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bcssafy?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: bcssafy
    password: bcssafy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: true
  web3j:
    client-address: http://localhost:8545
    admin-client: true
eth:
  encrypted:
    password: Pn0OlSN0SdhjNK5X2EhUPQ==
  erc721:
    contract: 7d2026d684f19deaa4134c39dde786605dcc90d4
  purchase:
    record:
      contract: 0x0c2BC3cAB0036D1E51734B4D6e6cb8BCB046A2C7
  admin:
    address: 718ca8088ae9c120551defcbbecfedc3b9761a1f
    wallet:
      filename: admin.wallet
jwt:
  token:
    header-type: JWT
    issuer: najakwha
    secret: b3JpX3RveV9wcm9qZWN0X3JlYWxfd29ybGRfamF2YV9zcHJpbmdfYm9vdF9zZWNyZXRfand0X3NhdWx0X2tleQo=
    access-time: 1800000  # 30분
cloud:
  aws:
    credentials:
      accessKey: AKIAVISGU4KSDZTO6LHK
      secretKey: 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
    s3:
      bucket: najakwha
    region:
      static: ap-northeast-2
    stack:
      auto: false