spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  session:
    store-type: redis
  redis:
    host: 3.34.135.3
    password:
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bcssafy?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: bcssafy
    password: bcssafy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 692886957287-663ep6r6ds8ee0oukr9f5mrqof57k6bj.apps.googleusercontent.com
            client-secret: pVQcqYjwp_7fYyYdOJfkd5rk
            scope: profile,email
          naver:
            client-id: qJONuabRwLzw44TBZavZ
            client-secret: 2fGz3R2u8B
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          kakao:
            client-id: 9157b7a28ea73a1fe1a6ab9d0ea8520e
            client-secret: 1PmERaoLIQ2tk5pEB3divxtkNmY4ONWe
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: profile,account_email
            client-name: kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  web3j:
    client-address: http://localhost:8545
    admin-client: true
eth:
  encrypted:
    password: Pn0OlSN0SdhjNK5X2EhUPQ==
  erc721:
    contract: fe031e1193f2ad53901ff9f33e3dd75586c074e0
  purchase:
    record:
      contract: 0x0c2BC3cAB0036D1E51734B4D6e6cb8BCB046A2C7
  admin:
    address: 718ca8088ae9c120551defcbbecfedc3b9761a1f
    wallet:
      filename: admin.wallet
logging.level:
  org.hibernate.SQL: debug
server:
  port: 8080
    # servlet:
  # context-path: /api

